coverage:
  status:
    patch: false
    project:
      default:
        target: auto
        threshold: 5%
comment:
  layout: "header"
  require_changes: true
  behavior: default
  flags: null
  paths: null