name: docs_ASTRA
channels:

  - defaults
dependencies:
    # Base depends
  - python
  - pip
  


  # Pip-only installs
  - pip:
    - -e ../
    - pydata-sphinx-theme
    - sphinx-design
    - sphinx-copybutton

